WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.102:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 16:58:32] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 16:58:32] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dhiraj.mehta/courses/udacity-cncf/nd064_course_1/project/techtrends/app.py", line 42, in post
    logging.debug("An article retrieved is : " + post[0]["title"])
TypeError: 'int' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 16:58:34] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.102:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dhiraj.mehta/courses/udacity-cncf/nd064_course_1/project/techtrends/app.py", line 43, in post
    logging.debug("An article retrieved is : " + post[0]["title"])
TypeError: 'int' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 17:00:43] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.102:3111/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 17:01:53] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 17:01:53] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dhiraj.mehta/courses/udacity-cncf/nd064_course_1/project/techtrends/app.py", line 43, in post
    logging.debug("An article retrieved is : " + post[0][4])
TypeError: 'int' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 17:01:55] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.102:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dhiraj.mehta/courses/udacity-cncf/nd064_course_1/project/techtrends/app.py", line 43, in post
    logging.debug("An article retrieved is : " + post[4])
IndexError: tuple index out of range
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 17:02:46] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.102:3111/ (Press CTRL+C to quit)
DEBUG:root:An article retrieved is : 2020 CNCF Annual Report
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 17:03:37] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 17:03:37] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.102:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /8 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/dhiraj.mehta/courses/udacity-cncf/nd064_course_1/project/techtrends/app.py", line 40, in post
    logging.debug("An with id  : " + post_id + "does not exisits.")
TypeError: can only concatenate str (not "int") to str
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 17:05:19] "[35m[1mGET /8 HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.0.102:3111/ (Press CTRL+C to quit)
DEBUG:root:An with id  : 8does not exisits.
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 17:05:48] "[33mGET /8 HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 17:05:48] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
2022-07-31 17:12:13,967 WARNING   * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2022-07-31 17:12:13,967 INFO      * Running on http://192.168.0.102:3111/ (Press CTRL+C to quit)
2022-07-31 17:12:19,270 INFO     An article with id  : 8 does not exisits.
2022-07-31 17:12:19,278 INFO     127.0.0.1 - - [31/Jul/2022 17:12:19] "[33mGET /8 HTTP/1.1[0m" 404 -
2022-07-31 17:12:19,339 INFO     127.0.0.1 - - [31/Jul/2022 17:12:19] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
